name: Terraform Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  terraform-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

        # --- TFLint install (official action) ---
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      # --- Run TFLint (root) ---
      - name: TFLint (root)
        run: tflint --init && tflint

      - name: Terraform fmt (recursive)
        run: terraform fmt -check -recursive

      - name: Terraform init (no backend)
        run: terraform init -backend=false -input=false

      - name: Terraform validate
        run: terraform validate